import "./globals.css";
import styles from "./styles/layout.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Firstsec from "./components/firstsec";
import Navbar from "./components/navbar";
// import Bootmobile from "./components/bootnavmobile";
import Sidebarmobile from "./components/sidebarmobile";
import Mobilesecnav from "./components/mobilesecnav";
import Footer from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className={styles.paren}>
          <Navbar />
          <Sidebarmobile />
          {/* <Bootmobile /> */}
          <Mobilesecnav />

          <Firstsec />
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
